import Head from 'next/head'
import { useState } from 'react'
import {DragDropContext, Droppable,Draggable} from '@hello-pangea/dnd'

const task = [
  {
    id:"1",
    text:"comer"
  },
  {
    id:"2",
    text:"almorzar"
  },{
    id:"3",
    text:"desayunar"
  },{
    id:"4",
    text:"dormir"
  },
  {
    id:"5",
    text:"levantarse"
  }
]
export default function Home() {
  const [tarea, setTarea] = useState(task)
  const reorder = (list, startIndex, endIndex) => {
    const result = Array.from(list);
    const [removed] = result.splice(startIndex, 1);
    result.splice(endIndex, 0, removed);
  
    return result;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DragDropContext 
        onDragEnd={(result) => {
          const {destination, source} = result
          if(!destination ){
            return
          } 
          if(source.index === destination.index 
            && source.droppableId === destination.droppableId){
              return
            }
            setTarea(prevTarea => reorder(prevTarea,source.index,source.destination))
        }}
      >
        <h1>Listado</h1>
        <Droppable droppableId='task'>
          {(provided) => (
            <ul className='task' {...provided.droppableProps} ref={provided.innerRef}>
              {
                tarea.map((tarea,index )=> (
                  <Draggable key={tarea.id} draggableId={tarea.id} index={index}>
                    {(provided) => <li ref={provided.innerRef}
                      {...provided.draggableProps}
                      {...provided.dragHandleProps}>{tarea.text}</li>}
                  </Draggable> 
                ))
              }
              {provided.placeholder}
            </ul>
          )
          }
        </Droppable>
        
      </DragDropContext>
    </>
  )
}
